# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 784f9511e6009d03e150733d4465584d7874de1f7604b8f4d59e08ca6a4967a2c260696fd1d6662eecd3001c46c59dc726f3813946bafb2d7c7d6808ce1a05dd

test:
  secret_key_base: 55147de6327f44fba913bc0625d091fa517c5163f142e8efa38f7df5f8d90f30733277729c48c2acfc102dd3dfe2fdda5858c490be01329ec2dd8d330561bc97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
